/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final_exam;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    int posData [] = new int [] { 5, 10, 2, 7, 8};
    int negData [] = new int [] { -4, -20, -1, -8, -3};
    int mixData [] = new int [] { 5, 5, 0, -10, -2, 100};
    
    App sortData = new App();

    @Test void testPositve() {

        int correctData [] = new int [] {2,5,7,8,10};
        sortData.selectionSort(posData);
        assertArrayEquals(posData, correctData);
    }

    @Test void testNegative() {

        int correctData [] = new int [] {-20,-8,-4,-3,-1};
        sortData.selectionSort(negData);
        assertArrayEquals(negData, correctData);
    }

    @Test void testMixed() {

        int correctData [] = new int [] {-10,-2,0,5,5,100};
        sortData.selectionSort(mixData);
        assertArrayEquals(mixData, correctData);
    }
}
